### PR TITLE
build: add pre-commit hooks

### PR DESCRIPTION
**Pull request by sbolel**
## Summary

This PR adds pre-commit hooks configuration that includes running the following hooks:

- bin files
    - `bin/rustfmt.sh` (runs `cargo fmt`)
    - `bin/clippy.sh` (runs `cargo clippy)
    - `bin/check.sh` (runs `cargo check`)
- check json
- check yaml
- check for case conflicts
- check for merge conflicts
- check for broken symlinks
- detect destroyed symlinks
- fix utf-8 byte order marker
- fix end of files
- trim trailing whitespace
- mixed line ending
- detect AWS credentials
- detect private keys
- detect hardcoded secrets using GitLeaks
- run `cargo test`

## TODO

- [x] use `aquia-inc/pre-commit-rust` repo
- add custom patterns for GitLeaks
  - [x] generic UUIDs (works by default)
  - [x] SBOM API tokens
- [x] clippy
- [x] run tests

## How to test

1. [install `pre-commit`](https://pre-commit.com/#install) and install [`gitleaks`](https://github.com/gitleaks/gitleaks#installing)
2. clean and build - `cargo clean; cargo build`
3. install the git hooks - `pre-commit install`
4. make a new file called `env` and put secrets you'd like to to test in it.
5. stage that file - `git add env`
6. try to commit - `git commit -m "chore: bad commit"
7. if the `pre-commit` step passes and a commit is authored, then that secret was missed and the test failed.

## Results

- checking for an `sbom-api-sbom-api-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[8|9aA|bB][0-9a-f]{3}-[0-9a-f]{12}` token:
-

### CODE REVIEW

**Comment by qtpeters** [comment]
So it looks like rustrfmt is formatting _all_ of the Rust files instead of the staged ones:

Below, one can see that I edited only one file:
image

After attempting to commit, rustfmt runs and then this:
image

**Review by qtpeters — CHANGES_REQUESTED** [review]
rustfmt is formatting more than staged files, please have it only format those.

**Comment by sbolel** [comment]
@qtpeters thanks for the heads up! will make that fi

**Review by qtpeters — APPROVED** [review]
Finally approved I hope

**Review by qtpeters — APPROVED** [review]
Not that lucky I guess

**Review by qtpeters — CHANGES_REQUESTED** [review]
Sorry!  I accidently approved this

**Comment by sbolel** [comment]
@qtpeters this is ready for review. I added shell scripts for running the formatters. rustfmt now runs only for staged files. However, I discovered that `clippy` is also checking all files but that doesn't seem to have a simple solution.

**Comment by qtpeters** [comment]
So, I tried again.  This time with this token: `sbom-api-abc123`.  Here are the results: 

image

I appears that `sbom-api-*` won't match because the actual regular expression being used to test the value in `env` is: '''sbom-api-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[8|9aA|bB][0-9a-f]{3}-[0-9a-f]{12}''' which would fail unless `sbpm-api` has a uuid after it.  Do you want to change the regular expression to be able to match `sbom-api-*`?  If so, I'll request changes, but if you are after only the pattern of the _generated_ tokens only, then I think you are good to go.

**Review by qtpeters — APPROVED** [review]
LGTM

**Pull request merged**
